### ISSUE TITLE
Downsampling example (part of phenology modelling?)

### ISSUE THREAD

**Issue by khufkens** [khufkens/handful_of_pixels#30]
Coordinate with @pepaaran 

- Use ERA5 daily means (introduce the concept of remotely executed scripts)
   - hybrid API / cloud computing approach
- complement with monthly values from WorldClim per {ingestr} routine-ish
- resample data to a common base
- do a gridded regression to extract required offsets
- calculate downsampled ERA5 data

**Comment by pepaaran** [comment]
For the downsampling of temperature and VPD, I used daily means from WATCH-WFDEI and followed this workflow:
- Read WATCH-WFDEI daily values, compute monthly means. 
- Compute monthly climatology by averaging monthly means between 1979-2000 (because WorldClim is between 1970-2000).
- Regrid WATCH-WFDEI monthly climatology to match WorldClim grid. 
- Compute bias for each month: 
$$\text{bias}_{i} = \text{clim}_{i}^{\text{WATCH}} - \text{clim}_{i}^{\text{WorldClim}}$$
- Regrid original daily files to match WorldClim, then substract bias for the corresponding month.

Here two images of the original temperature data (WATCH-WFDEI) and the regridded and de-biased data.
![image](https://github.com/khufkens/handful_of_pixels/assets/61271873/23f567aa-a320-49aa-935f-4f0aed9297fc)
![image](https://github.com/khufkens/handful_of_pixels/assets/61271873/b29ee8ec-e197-4257-aad4-772ab8d552ad)

If that workflow is useful for your use case, just use my code. I started from ingestr but I found it quite confusing and ended up doing it from scratch rather than modifying ingestr. This is the main function https://github.com/pepaaran/agds_proseminar_example/blob/main/R/downscale_t_vpd.R

**Comment by khufkens** [comment]
I just want to regress monthly temperature bias ~ DOY, as to avoid step changes and do less book keeping (storing only two parameters instead of monthly bias values).

**Comment by khufkens** [comment]
Thinking about this, it doesn't make sense. Anyway, there should be a way to translate this into something more simple, rather than storing all this data.

**Comment by pepaaran** [comment]
I just tried regressing monthly temperature bias on elevation and it looks like this: 

```
Call:
lm(formula = extract(clim_monthly_bias[[1]], crop_map)[, 2] ~ 
    extract(elv, crop_map)[, 2])

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7651 -0.9967  0.3226  1.2545  5.2915 

Coefficients:
                              Estimate Std. Error t value Pr(>|t|)    
(Intercept)                 -2.388e+00  1.173e-02  -203.5   <2e-16 ***
extract(elv, crop_map)[, 2]  1.738e-03  7.795e-06   223.0   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 1.596 on 68785 degrees of freedom
  (1317 observations deleted due to missingness)
Multiple R-squared:  0.4196,	Adjusted R-squared:  0.4196 
F-statistic: 4.974e+04 on 1 and 68785 DF,  p-value: < 2.2e-16
```

![image](https://github.com/khufkens/handful_of_pixels/assets/61271873/69183628-43d2-41cd-a012-42162fd336b8)

Note that the resampling was done with bilinear interpolation, I think the correlation would be higher if I had used mean interpolation.
